services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"